# version: '3.1'

services:

  db:
    image: mariadb
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 3360:3306
    volumes:
      - au_ptit_destock:/var/lib/mysql
    container_name: stage

volumes:
  au_ptit_destock: 
