version: '3.1'

services:

  db:
    image: mariadb
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 3360:3306
    volumes:
      - stage:/var/lib/mysql
    container_name: stage

volumes:
  stage: 
